export {
  createTypeComp,
  fromContext,
  type PersonQuery,
  type TypeComp,
} from './context';

export {
  accepted,
  ageBetween,
  allGroups,
  and,
  booleanProperty,
  canScramble,
  competingIn,
  competingInAll,
  competingInAny,
  everyone,
  forEvent,
  forRound,
  fromCountries,
  fromCountry,
  type GroupFilter,
  gender,
  groupNumber,
  groupNumberBetween,
  hasPB,
  hasProperty,
  hasRole,
  hasStaffAssignments,
  hasWcaId,
  isDelegate,
  isForeigner,
  isOrganizer,
  isStaffJudge,
  isStaffRunner,
  isStaffScrambler,
  isTraineeDelegate,
  nameContains,
  nameIs,
  newcomer,
  nobody,
  noGroups,
  nonCompeting,
  not,
  notCompetingIn,
  notCompetingInAny,
  numberPropertyBetween,
  numberPropertyEquals,
  numberPropertyGreaterThan,
  numberPropertyLessThan,
  olderThan,
  or,
  type PersonFilter,
  pbFasterThan,
  pbSlowerThan,
  registered,
  registrantId,
  registrantIds,
  staffAssignmentCountBetween,
  stringProperty,
  stringPropertyIn,
  wcaId,
  wcaIdAfter,
  wcaIdBefore,
  wcaIds,
  wcaIdYear,
  youngerThan,
} from './filters';

export * as presets from './presets';

export {
  assignAllRounds,
  assignBlindfolded,
  assignGroupifier,
  assignRound,
  assignStaff,
  defaultGroupScorers,
  type GroupifierOptions,
  type GroupifierResult,
  simpleGroupScorers,
  simpleStaffScorers,
} from './presets';
export {
  type AssignmentResult,
  GroupByBuilder,
  type GroupOptions,
  RoundBuilder,
  StationsBuilder,
} from './round-builder';

export {
  balancedScramblerScorer,
  byFilters,
  byMatchingValue,
  combineScorers,
  combineStaffScorers,
  conditionalScorer,
  consecutiveJobScorer,
  delegateDeprioritizer,
  differentFirstNames,
  fastestScrambler,
  followingGroupScorer,
  mismatchedStationScorer,
  preferenceScorer,
  priorAssignmentScorer,
  recentlyCompeted,
  type StaffScorer,
  sameCountry,
  sameJobScorer,
  sameWcaIdYear,
  spreadOut,
  staffScorer,
} from './scorers';
export { StaffBuilder, type StaffResult } from './staff-builder';

export {
  COMMON_STAGE_LAYOUTS,
  defineStages,
  type StageConfig,
  StageManager,
  singleStage,
  twoStages,
} from './stages';
