export {
  createTypeComp,
  fromContext,
  type PersonQuery,
  type TypeComp,
} from './context';
export {
  accepted,
  allGroups,
  and,
  type ContextualPersonFilter,
  canScramble,
  competingIn,
  competingInAll,
  competingInAny,
  everyone,
  forEvent,
  forRound,
  fromCountries,
  fromCountry,
  type GroupFilter,
  gender,
  groupNumber,
  groupNumberBetween,
  hasPB,
  hasRole,
  hasWcaId,
  isDelegate,
  isOrganizer,
  isTraineeDelegate,
  nameContains,
  nameIs,
  newcomer,
  nobody,
  noGroups,
  nonCompeting,
  not,
  notCompetingIn,
  notCompetingInAny,
  or,
  type PersonFilter,
  pbFasterThan,
  pbSlowerThan,
  registered,
  registrantId,
  registrantIds,
  wcaId,
  wcaIdAfter,
  wcaIdBefore,
  wcaIds,
  wcaIdYear,
} from './filters';
export * as presets from './presets';
export {
  assignBlindfolded,
  assignLaterRound,
  assignRound,
  assignStaff,
  assignWaveStaff,
  defaultGroupScorers,
  quickAssign,
  type SmallCompetitionOptions,
  type StandardStaffOptions,
  type WaveCompetitionOptions,
} from './presets';
export {
  type AssignmentResult,
  GroupByBuilder,
  type GroupOptions,
  RoundBuilder,
  StationsBuilder,
} from './round-builder';
export {
  byFilters,
  byMatchingValue,
  combineScorers,
  combineStaffScorers,
  differentFirstNames,
  fastestScrambler,
  recentlyCompeted,
  sameCountry,
  sameWcaIdYear,
  spreadOut,
  staffScorer,
} from './scorers';
export { StaffBuilder, type StaffResult } from './staff-builder';
